#!/bin/bash
cd $OPENSHIFT_REPO_DIR

export NPM_CONFIG_CACHE="$OPENSHIFT_TMP_DIR/npm/cache" 
export MAVEN_OPTS="-Dmaven.repo.local=$OPENSHIFT_TMP_DIR/m2" 
export HOME="$OPENSHIFT_TMP_DIR/local" 

npm install npm
export PATH="$OPENSHIFT_REPO_DIR/node_modules/.bin:$PATH"

mvn clean package
