FROM ibm-semeru-runtimes:open-21.0.6_7-jre@sha256:1515f0d2b2fade9d1930778f0af5a10d6360ef5c72bd432983df3a9cff3472ff
EXPOSE 8082

RUN mkdir -p /commafeed/data
VOLUME /commafeed/data

COPY artifacts/extracted-jvm-package/quarkus-app/ /commafeed
WORKDIR /commafeed

CMD ["java", \
    "-Xtune:virtualized", \
    "-Xminf0.05", \
    "-Xmaxf0.1", \
    "-jar", \
    "quarkus-run.jar"]
