FROM debian:12.10@sha256:87d30835e154dc4c54d3fbb70b835f0ed7ee7b4161b44006f127ff4365b66f94
ARG TARGETARCH

EXPOSE 8082

RUN mkdir -p /commafeed/data
VOLUME /commafeed/data

COPY artifacts/commafeed-*-${TARGETARCH}-runner /commafeed/application
WORKDIR /commafeed

CMD ["./application"]
