FROM ibm-semeru-runtimes:open-25-jre@sha256:8c5203fe1fa4fde77d8bc906d4d38f75e4e8e3d205721e8eb20b4b91388c49b7
EXPOSE 8082

RUN mkdir -p /commafeed/data
VOLUME /commafeed/data

COPY artifacts/extracted-jvm-package/quarkus-app/ /commafeed
WORKDIR /commafeed

CMD ["java", \
    "-Xtune:virtualized", \
    "-Xminf0.05", \
    "-Xmaxf0.1", \
    "-jar", \
    "quarkus-run.jar"]
