FROM ibm-semeru-runtimes:open-21.0.8_9-jre@sha256:0d2e27e83ccf97e8aa10ddbe3771811449b1ab5915428c3640cea4edc42d5c30
EXPOSE 8082

RUN mkdir -p /commafeed/data
VOLUME /commafeed/data

COPY artifacts/extracted-jvm-package/quarkus-app/ /commafeed
WORKDIR /commafeed

CMD ["java", \
    "-Xtune:virtualized", \
    "-Xminf0.05", \
    "-Xmaxf0.1", \
    "-jar", \
    "quarkus-run.jar"]
