name: ci

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [ "h2", "postgresql", "mysql", "mariadb" ]

    steps:
      # Checkout
      - name: Configure git to checkout as-is
        run: git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: "21"
          distribution: "graalvm"
          cache: "maven"

      # Build & Test
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress install -Pnative -D"quarkus.datasource.db-kind"=${{ matrix.database }}

      # Upload artifacts
      - name: Upload cross-platform app
        uses: actions/upload-artifact@v4
        with:
          name: commafeed-${{ matrix.database }}-jvm
          path: commafeed-server/target/commafeed-*.zip

      - name: Upload native executable
        uses: actions/upload-artifact@v4
        with:
          name: commafeed-${{ matrix.database }}-${{ runner.os }}-${{ runner.arch }}
          path: commafeed-server/target/commafeed-*-runner

      # Docker
      - name: Login to Container Registry
        uses: docker/login-action@v3
        if: ${{ github.ref_type == 'tag' || github.ref_name == 'master' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build and push tag - native
        uses: docker/build-push-action@v6
        if: ${{ github.ref_type == 'tag' }}
        with:
          context: commafeed-server
          file: src/main/docker/Dockerfile.native
          push: true
          platforms: linux/amd64
          tags: |
            athou/commafeed:latest
            athou/commafeed:${{ github.ref_name }}

      - name: Docker build and push tag - jvm
        uses: docker/build-push-action@v6
        if: ${{ github.ref_type == 'tag' }}
        with:
          context: commafeed-server
          file: src/main/docker/Dockerfile.jvm
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            athou/commafeed:latest-jvm
            athou/commafeed:${{ github.ref_name }}-jvm

      - name: Docker build and push master - native
        uses: docker/build-push-action@v6
        if: ${{ github.ref_name == 'master' }}
        with:
          context: commafeed-server
          file: src/main/docker/Dockerfile.native
          push: true
          platforms: linux/amd64
          tags: athou/commafeed:master

      - name: Docker build and push master - jvm
        uses: docker/build-push-action@v6
        if: ${{ github.ref_name == 'master' }}
        with:
          context: commafeed-server
          file: src/main/docker/Dockerfile.jvm
          push: true
          platforms: linux/amd64
          tags: athou/commafeed:master-jvm
