name: Update Docker Hub Description

on: release

jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: athou/commafeed
          short-description: ${{ github.event.repository.description }}
          readme-filepath: commafeed-server/src/main/docker/README.md