name: SonarQube

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

env:
  JAVA_VERSION: 25

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      # Setup
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@aba6a077d71fbfc02138d7470c4ad6e7f85bd2a9 # v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "graalvm"
          cache: "maven"

      - name: Install Playwright dependencies
        run: sudo apt-get install -y libgbm1

      # Run test coverage and SonarQube analysis
      - name: Analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn --batch-mode verify sonar:sonar -Dsonar.projectKey=Athou_commafeed
